### ISSUE TITLE
CallCodeGenerator is pushing args on the stack if there are > 3 (should be > 4)

### ISSUE THREAD

**Issue by dplassgit** [dplassgit/d2lang#253]
https://github.com/dplassgit/d2lang/blob/18378e5779f29ca3c3e9f01dfa9d99ba43bf9eae/src/com/plasstech/lang/d2/codegen/x64/CallCodeGenerator.java#LL77C1-L78C1

**Comment by dplassgit** [comment]
This isn't tragic because the subsequent loop stops at argument 5 as expected.

**Comment by sailee987** [comment]
How to run the project and view the output

**Comment by dplassgit** [comment]
> How to run the project and view the output

See the README: https://github.com/dplassgit/d2lang#installing

**Comment by sailee987** [comment]
I have imported the project in eclipse. How to run the project to view the output?

![JavaProject](https://github.com/dplassgit/d2lang/assets/62833306/6f42f7ac-7fb6-4f9c-b867-1a90f08f8ff6)

**Comment by dplassgit** [comment]
This project is a compiler. There is no UI so you can't just "run the project."

If you want to run a test, find the test in the package explorer and use the "Run" menu: Run/Run as/JUnit Test. 

You can probably start with NasmCodeGeneratorProcTest.java to see if anything breaks.

As mentioned in the [README ](https://github.com/dplassgit/d2lang#installing) you must have nasm and gcc installed, even when running within Eclipse.

For more information about how to use Eclipse, try www.eclipse.org

**Comment by Ankit8848** [comment]
@dplassgit is this issue  resolved?

**Comment by dplassgit** [comment]
> 

No.

**Comment by Ankit8848** [comment]
@dplassgit sir, here only  I have to change  ```3 to 4``` ?

**Comment by dplassgit** [comment]
> @dplassgit sir, here only I have to change `3 to 4` ?

Pretty much, yes. I don't think it's feasible to write a targeted test for that bugfix
