### ISSUE TITLE
Replace "foo" with a more meaningful variable name in the op= parse code

### ISSUE THREAD

**Issue by dplassgit** [dplassgit/d2lang#301]
https://github.com/dplassgit/d2lang/blob/58d557408e6ef667cc488742e943e9325022e7d5/src/com/plasstech/lang/d2/parse/Parser.java#L290

**Comment by 724thomas** [comment]
hi, i searched good first issue on explore tab and arrived here :)
maybe foo --> binaryOperationResult?

**Comment by dplassgit** [comment]
> hi, i searched good first issue on explore tab and arrived here :) maybe foo --> binaryOpNode?

That's not meaningful. Maybe rename "rhs" to "originalRhs" and "foo" to "newRhs"

**Comment by ghanghavmayur** [comment]
Sir can you please review PR #308

**Comment by dplassgit** [comment]
Will do. Note, I am in the Eastern US zone so I may not have time to work on this until much later today.

**Comment by ghanghavmayur** [comment]
No problem at all, sir! If there's any mistake or if you have any suggestions, please  let me know. Your guidance is highly valued.
