### ISSUE TITLE
Universal Process Notation (UPN) support

### ISSUE THREAD

**Issue by mantielero** [dplassgit/d2lang#322]
It would be great being able to draw UPN diagrams with D2. They are used to describe processes in a simple way (as opposed to BPMN which is way more complex). 

The spec is [here](https://www.imperial.ac.uk/media/imperial-college/administration-and-support-services/operational-excellence/public/Quick-Start-Guide-to-Universal-Process-Notation.pdf) -about 15 pages-.

And some examples (taken from this [bug report](https://github.com/jgraph/drawio/issues/1031):
https://elements.cloud/2016/06/01/upn/
https://www.salesforceben.com/introduction-to-universal-process-notation-upn-for-salesforce-processes-mapping/
https://www.tibco.com/resources/whitepaper/universal-process-notation-simple-solution-complex-process-diagrams

It looks pretty simple, compare to what D2 is already capable to do.

**Comment by dplassgit** [comment]
That's not really anything I'm interested in the language to do. Note, there is already interop with C libraries so it's possible to use `extern` to call an external library already.

**Comment by prog110** [comment]
@mantielero You seemed to have opened the issue in the wrong d2 project. You seemed to have already raised one [there](https://github.com/terrastruct/d2/issues/1702) too.

**Comment by mantielero** [comment]
Oops. I don't know how I mixed this up. Sorry guys for the noise. And good luck with your project.
